name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 08:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Villoh/github-activity-readme@commit-username-and-email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}