on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'  # Every day at 08:00 UTC

jobs:
  top-followers:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 💾 Check for README changes
        id: readme_check
        run: |
          echo "::group::Generate before hash"
          BEFORE_HASH=$(md5sum README.md | cut -d ' ' -f1)
          echo "before_hash=$BEFORE_HASH" >> $GITHUB_ENV
          echo "::endgroup::"

      - name: 🧠 Update README with top followers
        run: python src/getTopFollowers.py ${{ github.repository_owner }} ${{ secrets.GITHUB_TOKEN }} README.md

      - name: 🔁 Compare README hash after script
        id: hash_check
        run: |
          AFTER_HASH=$(md5sum README.md | cut -d ' ' -f1)
          echo "after_hash=$AFTER_HASH" >> $GITHUB_ENV

      - name: ✅ Commit changes (only if hash changed)
        if: env.before_hash != env.after_hash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "🔄 Update top followers"

      - name: 🚀 Push changes
        if: env.before_hash != env.after_hash
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}